apiVersion: v1
kind: Pod
metadata:
  name: {{ include "omsk-time.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  containers:
  - name: post-install-job
    image: busybox
    command: ['sh', '-c', 'echo "Starting post-install hook"; sleep 20; echo "Post-install hook completed"']
