- name: Ensure web_app_dir exists
  ansible.builtin.file:
    path: "{{ web_app_dir }}"
    state: directory
    mode: '0755'
  when: web_app_full_wipe

- name: Check if docker-compose.yml exists
  ansible.builtin.stat:
    path: "{{ web_app_dir }}/docker-compose.yml"
  register: compose_file

- name: Wipe images
  community.docker.docker_compose_v2:
    project_src: "{{ web_app_dir }}"
    remove_orphans: true
    remove_volumes: true
    remove_images: all
    state: absent
  when: compose_file.stat.exists

- name: Remove app directory
  ansible.builtin.file:
    path: "{{ web_app_dir }}"
    state: absent
