---

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "grafana"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "moscow-time-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["moscow-time-app:8080"]

  - job_name: "omsk-time-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["omsk-time-app:8081"]
