apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: moscow-time.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moscow-time-service
            port:
              number: 80
  - host: omsk-time.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omsk-time-service
            port:
              number: 80
