- name: Deploy app_python
  hosts: all
  become: true
  roles:
    - web_app
  vars:
    web_app_name: moscow-time
    web_app_internal_port: 8080
    web_app_external_port: 8080
    web_app_full_wipe: true
