- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's official apt repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker and dependencies
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: ansible_user != 'root'
  notify: Restart Docker

- name: Configure Docker security settings
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "userns-remap": "default"
      }
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker

- name: Enable Docker service to start on boot
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
